# Generated by Django 5.0.7 on 2024-07-31 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acionista',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('segundo_nome', models.CharField(max_length=255)),
                ('apelido', models.CharField(max_length=255)),
                ('data_de_nascimento', models.DateField()),
                ('identificacao', models.CharField(max_length=20, unique=True)),
                ('nuit', models.CharField(max_length=20, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiretorCurso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('segundo_nome', models.CharField(max_length=255)),
                ('apelido', models.CharField(max_length=255)),
                ('data_de_nascimento', models.DateField()),
                ('identificacao', models.CharField(max_length=20, unique=True)),
                ('nuit', models.CharField(max_length=20, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, max_length=2000, null=True)),
                ('diretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sge_api.diretorcurso')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=225)),
                ('apelido', models.CharField(max_length=225)),
                ('data_de_nascimento', models.DateField()),
                ('identificacao', models.CharField(max_length=20, unique=True)),
                ('data_de_emissao', models.DateField()),
                ('data_de_validade', models.DateField()),
                ('nuit', models.CharField(max_length=20, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('formacao', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('descricao', models.TextField()),
                ('docente_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='sge_api.docente')),
            ],
        ),
        migrations.CreateModel(
            name='DocenteDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sge_api.disciplina')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sge_api.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=225)),
                ('apelido', models.CharField(max_length=225)),
                ('data_de_nascimento', models.DateField()),
                ('identificacao', models.CharField(max_length=20, unique=True)),
                ('nuit', models.CharField(max_length=20, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SemestreLectivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semestre', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='sge_api.curso')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='sge_api.semestrelectivo'),
        ),
    ]
