# Generated by Django 5.0.7 on 2024-07-31 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sge_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('segundo_nome', models.CharField(max_length=225)),
                ('apelido', models.CharField(max_length=225)),
                ('data_de_nascimento', models.DateField()),
                ('numero_de_bi', models.CharField(max_length=20, unique=True)),
                ('data_de_emissao', models.DateField()),
                ('data_de_validade', models.DateField()),
                ('nuit', models.CharField(max_length=20, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('nome_do_pai', models.CharField(max_length=600)),
                ('nome_da_mae', models.CharField(max_length=600)),
                ('escola_anterior', models.CharField(max_length=400)),
                ('ano_conclusao', models.DateField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstudanteDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sge_api.disciplina')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sge_api.estudante')),
            ],
        ),
    ]
