# Generated by Django 5.0.7 on 2024-08-02 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sge_api', '0003_remove_estudantedisciplina_disciplina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exame', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exame_recorrencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sge_api.disciplina')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sge_api.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_pagamento', models.CharField(choices=[('matricula', 'Matrícula'), ('mensalidade', 'Mensalidade')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField()),
                ('metodo_pagamento', models.CharField(max_length=50)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='sge_api.estudante')),
            ],
        ),
    ]
