# Generated by Django 5.0.7 on 2024-08-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sge_api', '0004_avaliacao_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateField(auto_now_add=True),
        ),
    ]
