# Generated by Django 5.0.7 on 2024-08-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sge_api', '0005_alter_pagamento_data_pagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudantedisciplina',
            old_name='disciplina',
            new_name='disciplinas',
        ),
    ]
