# Generated by Django 5.0.7 on 2024-08-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sge_api', '0006_rename_disciplina_estudantedisciplina_disciplinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='mes_referente',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
