# Generated by Django 5.0.7 on 2024-08-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sge_api', '0007_pagamento_mes_referente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docentedisciplina',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='docentedisciplina',
            name='disciplina',
            field=models.ManyToManyField(to='sge_api.disciplina'),
        ),
    ]
