# Generated by Django 5.0.7 on 2024-08-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sge_api', '0008_remove_docentedisciplina_disciplina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='exame',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='exame_recorrencia',
        ),
        migrations.CreateModel(
            name='Exames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exame', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exame_recorrencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sge_api.disciplina')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sge_api.estudante')),
            ],
        ),
    ]
