# Generated by Django 5.0.7 on 2024-08-24 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sge_api', '0009_remove_avaliacao_exame_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudanteCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sge_api.curso')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sge_api.estudante')),
            ],
            options={
                'verbose_name': 'Estudante Curso',
                'verbose_name_plural': 'Estudantes Cursos',
                'unique_together': {('estudante', 'curso')},
            },
        ),
    ]
