# Generated by Django 5.0.7 on 2024-08-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sge_api', '0010_estudantecurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='genero',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudante',
            name='nacionalidade',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
