# Generated by Django 5.0.7 on 2024-08-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sge_api', '0011_estudante_genero_estudante_nacionalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='percent_nota1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='percent_nota2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='percent_nota3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='percent_nota4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='mes_referente',
            field=models.CharField(choices=[('janeiro', 'Janeiro'), ('fevereiro', 'Fevereiro'), ('marco', 'Março'), ('abril', 'Abril'), ('maio', 'Maio'), ('junho', 'Junho'), ('julho', 'Julho'), ('agosto', 'Agosto'), ('setembro', 'Setembro'), ('outubro', 'Outubro'), ('novembro', 'Novembro'), ('dezembro', 'Dezembro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo_pagamento',
            field=models.CharField(choices=[('numerario', 'Numerário'), ('m-pesa', 'M-Pesa'), ('e-mola', 'E-Mola'), ('bim', 'BIM')], max_length=20),
        ),
    ]
